version: 2
jobs:
  build:
    docker:
      - image: circleci/node:9


    working_directory: ~/repo

    steps:
      # Checkout and restore dependency cache
      - checkout
      - restore_cache:
          key: v2-dependencies-{{ checksum "yarn.lock" }}

      # Download and cache dependencies
      - run: yarn global add greenkeeper-lockfile@1 --prefix ~/repo
      - run: ~/repo/bin/greenkeeper-lockfile-update
      - run: yarn install
      - save_cache:
          key: v2-dependencies-{{ checksum "yarn.lock" }}
          paths:
            - "node_modules"

      - run: yarn build
      - run: yarn format

      # run tests and report the coverage
      - run: yarn test --coverage && yarn report-coverage

      - run: ~/repo/bin/greenkeeper-lockfile-upload
